# Copyright 2018 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file creates a build environment for building and running kubernetes
# unit and integration tests

FROM golang:1.10.2
LABEL authors="James Munnelly <james@jetstack.io>"

# Setup workspace and symlink to gopath
WORKDIR /workspace
RUN mkdir -p /go/src/github.com/jetstack/cert-manager /workspace \
    && ln -s /go/src/github.com/jetstack/cert-manager /workspace/cert-manager
ENV WORKSPACE=/workspace \
    TERM=xterm

# Install linux packages
# bc is needed by shell2junit
# dnsutils is needed by federation cluster scripts.
# file is used when uploading test artifacts to GCS.
# jq is used by hack/verify-godep-licenses.sh
# python-pip is needed to install the AWS cli.
# netcat is used by integration test scripts.
RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get install -y \
        bc \
	dnsutils \
	file \
	jq \
	python-pip \
	netcat-openbsd \
	rsync \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -L https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 >/tmp/dep \
    && curl -L https://github.com/mikefarah/yaml/releases/download/1.13.1/yaml_linux_amd64 >/tmp/yaml \
    && curl -L https://github.com/Masterminds/vert/releases/download/v0.1.0/vert-v0.1.0-linux-amd64 >/tmp/vert \
    && curl -Lo helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.9.0-linux-amd64.tar.gz \
    && curl -Lo /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl \
    && tar xvf helm.tar.gz \
    && chmod +x /tmp/dep \
    && chmod +x /tmp/yaml \
    && chmod +x /tmp/vert \
    && chmod +x /tmp/kubectl \
    && mv /tmp/dep /tmp/yaml /tmp/vert /tmp/kubectl /usr/local/bin/ \
    && mv linux-amd64/helm /usr/local/bin

RUN go get -v golang.org/x/tools/cmd/goimports \
    && go get -v github.com/golang/lint/golint
